### ISSUE TITLE
Implement Traffic Limits in Nginx Ingress

### ISSUE THREAD

**Issue by thinhfromtop** [digitopvn/diginext#536]
**Is your feature request related to a problem? Please describe.**
Currently, our system is experiencing issues with high traffic, leading to overload and impacting performance. We need a solution to limit the number of connections and requests per second from specific IP addresses.

**Describe the solution you'd like**
We want to add traffic limits to the Nginx Ingress as follows:

```
nginx.ingress.kubernetes.io/limit-burst: '30'
nginx.ingress.kubernetes.io/limit-connections: '10'
nginx.ingress.kubernetes.io/limit-rps: '20'
nginx.ingress.kubernetes.io/limit-whitelist: xxx.xxx.xxx.xxx/24
```

**Describe alternatives you've considered**
We have considered other solutions such as using a WAF (Web Application Firewall) or a CDN (Content Delivery Network) to manage traffic, but these solutions are more complex and costly. Using Nginx Ingress with traffic limits appears to be a simpler and more effective solution.

**Additional context**
To facilitate quick and effective deployment, we need a clear and detailed request on how to configure these limits in Nginx Ingress. Below is an example of the configuration to be added:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
  annotations:
    nginx.ingress.kubernetes.io/limit-burst: '30'
    nginx.ingress.kubernetes.io/limit-connections: '10'
    nginx.ingress.kubernetes.io/limit-rps: '20'
    nginx.ingress.kubernetes.io/limit-whitelist: xxx.xxx.xxx.xxx/24
spec:
  rules:
  - host: example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: example-service
            port:
              number: 80
```
Thank you for considering our request.
